displayName: Dynamic Redirects
iconPath: .assets/icon.png
import: github.com/DoodleScheduling/traefik-dynamic-redirects
summary: Middleware for dynamic redirects based on cookies and Accept-Language.
testData:
  redirects:
  - authenticatedCookie: Authentication
    authenticatedTarget: https://example.com/home/
    defaultTarget: https://example.com/en/
    localeCookie: locale
    localeTargets:
      de: https://example.com/de/
      es: https://example.com/es/
      fr: https://example.com/fr/
      it: https://example.com/it/
    preserveQueryString: true
    sourceURL: https://example.com/
    statusCode: 302
  - authenticatedCookie: Authentication
    authenticatedTarget: https://example.com/home/
    defaultTarget: https://example.com/en/
    localeCookie: locale
    localeTargets:
      de: https://example.com/de/
      es: https://example.com/es/
      fr: https://example.com/fr/
      it: https://example.com/it/
    preserveQueryString: true
    sourceURL: https://www.example.com/
    statusCode: 302
type: middleware
